### ISSUE TITLE
Current list (`class_names.txt`) is incomplete

### ISSUE THREAD

**Issue by xpe** [venkatasg/DeTeXt-Supplementary#1]
How do you generate https://github.com/venkatasg/DeTeXt-Supplementary/blob/main/class_names.txt ?

It isn't complete.

As an example of two missing LaTeX commands, see: https://github.com/venkatasg/DeTeXt/issues/6. I'd expect there are many more missing.

This is the definitive list of LaTeX symbols: https://ctan.org/pkg/comprehensive?lang=en

**Comment by venkatasg** [comment]
Closing this issue since I've said in another issue on the main repo, the list of symbols depends on the symbols for which we have training data. Generating training data is costly and time-consuming, and beyond the scope of a free utility app.
